apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres_dsp
    type: postgres
    access: proxy
    url: db:5432
    database: $POSTGRES_DB
    user: $POSTGRES_USER
    isDefault: true
    editable: true
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
